### ISSUE TITLE
Problem with preprocessing

### ISSUE THREAD

**Issue by yul091** [MengtingWan/grocery#1]
Hi, when I run the preprocessing py file, here comes the error:
Traceback (most recent call last):
  File "./src/parser.py", line 98, in <module>
    parse_instacart(thr_i = args.thr_item, thr_u = args.thr_user, subset_user = args.subset_user)
  File "./src/parser.py", line 80, in parse_instacart
    item_descr['PID'] = item_descr['PID'].apply(lambda x: [item_dict[k] for k in x])
  File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 4042, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2228, in pandas._libs.lib.map_infer
  File "./src/parser.py", line 80, in <lambda>
    item_descr['PID'] = item_descr['PID'].apply(lambda x: [item_dict[k] for k in x])
TypeError: 'int' object is not iterable

Actually I don't know why here comes this error? Thanks.

**Comment by 94akshayraj** [comment]
> Hi, when I run the preprocessing py file, here comes the error:
> Traceback (most recent call last):
> File "./src/parser.py", line 98, in
> parse_instacart(thr_i = args.thr_item, thr_u = args.thr_user, subset_user = args.subset_user)
> File "./src/parser.py", line 80, in parse_instacart
> item_descr['PID'] = item_descr['PID'].apply(lambda x: [item_dict[k] for k in x])
> File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 4042, in apply
> mapped = lib.map_infer(values, f, convert=convert_dtype)
> File "pandas/_libs/lib.pyx", line 2228, in pandas._libs.lib.map_infer
> File "./src/parser.py", line 80, in
> item_descr['PID'] = item_descr['PID'].apply(lambda x: [item_dict[k] for k in x])
> TypeError: 'int' object is not iterable
> 
> Actually I don't know why here comes this error? Thanks.

You can simply edit of line 80's lambda function to (lambda x: item_dict[x])
